"""The data-source contract.

FuelGrid's core (state, forecasting, optimisation, decisions, UI) talks only to this interface. Two adapters ship with it:

    SimulatorClient  (app/simulator/client.py)   the organizer's simulator over REST + SSE
    FeedSource       (app/adapters/feed.py)      a generic live feed: any system pushes topology and telemetry over HTTP
                                                 and pulls dispatch orders back

A new source (a CSV replay, a message queue, an ERP connector) only has to implement these members. Everything returns the
canonical types from app.domain.models and raises the errors from app.domain.errors."""
from typing import Protocol, runtime_checkable

from app.domain import models as M


@runtime_checkable
class DataSource(Protocol):
    kind: str                    # "simulator" | "feed" | ...
    label: str                   # human-readable name for the UI
    supports_admin: bool         # can the console inject events / faults / step the clock?
    supports_stream: bool        # does the source push change notifications (else we poll)?
    last_error: str | None
    last_stale: bool             # the latest read carried a "data may be stale" signal

    @property
    def breaker_open(self) -> bool: ...

    async def instance(self) -> M.Instance: ...
    async def regions(self) -> list[M.Region]: ...
    async def depots(self) -> list[M.Depot]: ...
    async def stations(self) -> list[M.Station]: ...
    async def routes(self) -> list[M.Route]: ...
    async def supply_arrivals(self) -> list[M.SupplyArrival]: ...
    async def events(self) -> list[M.SimEvent]: ...
    async def allocations(self) -> list[M.Allocation]: ...
    async def metrics(self) -> M.Metrics: ...
    async def demand_history(self, station_id: str | None = None, limit: int = 2000) -> list[M.DemandRow]: ...
    async def create_allocation(self, req: M.AllocationRequest) -> M.Allocation: ...
    async def aclose(self) -> None: ...
